import {
  AlignmentType,
  Document as DocxDocument,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import { IDocument } from '../models/Document';

const formatPercent = (value?: number): string => {
  if (typeof value !== 'number' || Number.isNaN(value)) {
    return 'N/A';
  }
  return `${(value * 100).toFixed(1)}%`;
};

const formatDate = (value?: Date): string => {
  if (!value) {
    return 'N/A';
  }
  return new Date(value).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
};

export class ReportGeneratorService {
  static async generatePlagiarismDocx(document: IDocument): Promise<Buffer> {
    const analysis = document.analysis;
    const now = new Date();

    const title = new Paragraph({
      alignment: AlignmentType.CENTER,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 280 },
      children: [new TextRun({ text: 'Plague Professional Similarity Report', bold: true })],
    });

    const subtitle = new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 380 },
      children: [
        new TextRun({
          text: `Generated on ${formatDate(now)} for ${document.originalName}`,
          italics: true,
        }),
      ],
    });

    const metricsTable = new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph('AI-Generated Score')] }),
            new TableCell({ children: [new Paragraph(formatPercent(analysis?.aiScore))] }),
            new TableCell({ children: [new Paragraph('Plagiarism Score')] }),
            new TableCell({ children: [new Paragraph(formatPercent(analysis?.plagiarismScore))] }),
          ],
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph('Similarity Score')] }),
            new TableCell({ children: [new Paragraph(formatPercent(analysis?.similarityScore))] }),
            new TableCell({ children: [new Paragraph('Confidence')] }),
            new TableCell({ children: [new Paragraph(formatPercent(analysis?.confidence))] }),
          ],
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph('Word Count')] }),
            new TableCell({
              children: [new Paragraph(document.extractedText.split(/\s+/).filter(Boolean).length.toString())],
            }),
            new TableCell({ children: [new Paragraph('Generated In')] }),
            new TableCell({
              children: [new Paragraph(`${analysis?.reportGeneratedInMs ?? 0} ms`)],
            }),
          ],
        }),
      ],
    });

    const flaggedHeading = new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 380, after: 180 },
      children: [new TextRun('Flagged Sections')],
    });

    const flaggedParagraphs =
      analysis?.flaggedSections?.length
        ? analysis.flaggedSections.slice(0, 10).map((section, index) => {
            const typeLabel =
              section.type === 'ai-generated' ? 'AI-generated' : 'Potential plagiarism';
            return new Paragraph({
              spacing: { after: 130 },
              children: [
                new TextRun({
                  text: `${index + 1}. ${typeLabel} (${formatPercent(section.confidence)} confidence): `,
                  bold: true,
                }),
                new TextRun(`"${section.text}"`),
              ],
            });
          })
        : [new Paragraph('No notable flagged sections were detected.')];

    const sourcesHeading = new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 280, after: 180 },
      children: [new TextRun('Top Source Matches')],
    });

    const sourceParagraphs =
      analysis?.sourceMatches?.length
        ? analysis.sourceMatches.slice(0, 5).map((match, index) => {
            return new Paragraph({
              spacing: { after: 110 },
              children: [
                new TextRun({
                  text: `${index + 1}. ${match.sourceName} (${match.sourceType}) - `,
                  bold: true,
                }),
                new TextRun(`${match.matchPercentage}% matched`),
              ],
            });
          })
        : [new Paragraph('No source matches were available for this report.')];

    const note = new Paragraph({
      spacing: { before: 360 },
      children: [
        new TextRun({
          text: 'Note: This report is generated by automated heuristics and should be reviewed alongside academic judgment.',
          italics: true,
        }),
      ],
    });

    const doc = new DocxDocument({
      sections: [
        {
          children: [
            title,
            subtitle,
            new Paragraph({
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 120, after: 180 },
              children: [new TextRun('Summary Metrics')],
            }),
            metricsTable,
            flaggedHeading,
            ...flaggedParagraphs,
            sourcesHeading,
            ...sourceParagraphs,
            note,
          ],
        },
      ],
    });

    return Packer.toBuffer(doc);
  }
}

export default ReportGeneratorService;
